### ISSUE TITLE
Add-on Startup Failed on Anki 23.10

### ISSUE THREAD

**Issue by GBergatto** [LeoWang2007/write-on-screen-anki#9]
When trying to run this add-on on Anki 23.10.1, I get the following error message:
```
Anki 23.10.1 (fac9e0e) Python 3.11.6 Qt 6.6.1 PyQt 6.6.1
Platform: Linux-6.6.7-arch1-1-x86_64-with-glibc2.38
Flags: frz=False ao=True sv=3
Add-ons, last update check: 2023-12-23 08:19:36

When loading Write on your screen:
Traceback (most recent call last):
  File "/home/gb/.local/share/Anki2/addons21/567651868/__init__.py", line 481, in ts_setup_menu
    mw.addon_view_menu
AttributeError: 'AnkiQt' object has no attribute 'addon_view_menu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/aqt/addons.py", line 245, in loadAddons
    __import__(addon.dir_name)
  File "/home/gb/.local/share/Anki2/addons21/567651868/__init__.py", line 519, in <module>
    ts_onload()
  File "/home/gb/.local/share/Anki2/addons21/567651868/__init__.py", line 183, in ts_onload
    ts_setup_menu()
  File "/home/gb/.local/share/Anki2/addons21/567651868/__init__.py", line 483, in ts_setup_menu
    mw.addon_view_menu = QMenu(_(u"&View"), mw)
                         ^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QMenu(parent: Optional[QWidget] = None): argument 1 has unexpected type 'str'
  QMenu(title: Optional[str], parent: Optional[QWidget] = None): argument 2 has unexpected type 'AnkiQt'
```

I've opened the same [issue](https://github.com/krassowski/Anki-TouchScreen/issues/28) on the orginal repo, and I've provided a fix in a [PR](https://github.com/krassowski/Anki-TouchScreen/pull/29) by changing all imports to use `aqt.qt`. 
I hope this helps.

**Comment by LeoWang2007** [comment]
I have fixed it. Now it can be run in the anki version 23.12.1, I think anki version 23.10.1 can run correctly too. If it also have something wrong, please tell me.

**Comment by LeoWang2007** [comment]
You can get it with addon code: 567651868.
Sorry for the wait.

**Comment by LeoWang2007** [comment]
You can get it with addon code: 567651868 directly in anki.
Sorry for the wait.

**Comment by GBergatto** [comment]
Thanks for the fix. I can confirm that it runs on Anki 23.12.1. I also appreciate the fact that you you have published the code as well.
